apiVersion: v1
kind: Service
metadata:
  name: {{ include "mautrix-instagram.fullname" . }}
  labels:
    {{- include "mautrix-instagram.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.config.metrics.enabled }}
    - port: {{ .Values.config.metrics.listen_port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
  selector:
    {{- include "mautrix-instagram.selectorLabels" . | nindent 4 }}
