{{- if and .Values.haproxy.serviceAccount.create .Values.haproxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "redis-ha.serviceAccountName" . }}-haproxy
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "redis-ha.labels" . | nindent 4 }}
    app.kubernetes.io/component: haproxy
    {{- range $key, $value := .Values.extraLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
