# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: master
chart-dirs:
  - charts
helm-extra-args: --debug --timeout 60s
check-version-increment: false
validate-maintainers: false
