# See https://github.com/helm/chart-testing#configuration
remote: origin
target-branch: master
chart-dirs:
  - charts
helm-extra-args: --debug
check-version-increment: true
validate-maintainers: false
