{{- with .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ha-eufy-sdk-bridge.fullname" $ }}
  labels:
    {{- include "ha-eufy-sdk-bridge.labels" $ | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
