{{- include "mautrix-telegram.configEnv.validate" . -}}
{{- if and .Values.configEnv.enabled (not .Values.configEnv.existingSecret) .Values.configEnv.secretEnv -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautrix-telegram.fullname" . }}-config-env
  labels:
    {{- include "mautrix-telegram.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.configEnv.secretEnv }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end -}}
