apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautrix-facebook.fullname" . }}
  labels:
{{ include "mautrix-facebook.labels" . | indent 4 }}
type: Opaque
data:
  registration.yaml: {{ .Values.registration | toYaml | b64enc | quote }}
