apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mautrix-meta.fullname" . }}
  labels:
{{ include "mautrix-meta.labels" . | indent 4 }}
data:
  config.yaml: {{ .Values.config | toYaml | quote }}
