apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "charts.fullname" . }}-config
  labels:
  {{- include "charts.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.configuration }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  DOH_SERVER_LISTEN: ":{{ .Values.service.port }}"
