{{- $imageTag := print (coalesce .Values.image.tag .Chart.AppVersion) "-" .Values.image.flavour -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.fullname" . }}
  labels:
  {{- include "charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
    {{- include "charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
      {{- include "charts.selectorLabels" . | nindent 8 }}
    spec:
      securityContext: {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: "doh-server"
        image: {{ .Values.image.repository }}:{{ $imageTag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "charts.fullname" . }}-config
        resources: {{- toYaml .Values.resources | nindent 10 }}
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
        {{- with .Values.livenessProbe }}
        livenessProbe: {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe: {{- toYaml . | nindent 10 }}
        {{- end }}
