{{- if .Values.monitoring.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "mosquitto.fullname" . }}
  {{- with .Values.monitoring.podMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels: {{- include "mosquitto.labels" . | nindent 4 }}
  {{- with .Values.monitoring.podMonitor.labels }}
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  podMetricsEndpoints:
    - interval: 15s
      port: metrics
      path: /metrics
      {{- with .Values.monitoring.podMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with .Values.monitoring.podMonitor.bearerTokenFile }}
      bearerTokenFile: {{ . }}
      {{- end }}
      {{- with .Values.monitoring.podMonitor.bearerTokenSecret }}
      bearerTokenSecret:
        name: {{ .name }}
        key: {{ .key }}
        {{- with .optional }}
        optional: {{ . }}
        {{- end }}
      {{- end }}
  jobLabel: {{ template "mosquitto.fullname" . }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mosquitto.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
