apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels: {{- include "mosquitto.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.ports }}
  ports:
  {{- range $key, $value := . }}
    - name: {{ $key }}
      port: {{ $value.port }}
      {{- with $value.nodePort }}
      nodePort: {{ . }}
      {{- end }}
      targetPort: {{ $key }}
      protocol: {{ default "TCP" $value.protocol }}
  {{- end }}
  {{- end }}
  {{- if .Values.monitoring.sidecar.enabled }}
    - name: metrics
      port: {{ .Values.monitoring.sidecar.port }}
    {{- with .Values.monitoring.sidecar.nodePort }}
      nodePort: {{ . }}
    {{- end }}
      targetPort: metrics
      protocol: TCP
  {{- end }}
  selector: {{- include "mosquitto.selector" . | nindent 4 }}
